#!/usr/bin/env bash
# scripts/linux/09-shell-profile.sh
# Deploys shell profiles, developer aliases, and environment variables on Linux

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Source modules
# shellcheck disable=SC1091
source "$ROOT_DIR/modules/linux/logging.sh"

log_header "Phase 9: Shell Profile & Developer Aliases"

TARGET_USER="${SUDO_USER:-$USER}"
TARGET_HOME=$(eval echo "~$TARGET_USER")

# 1. System-wide Profile in /etc/profile.d/burnandbuild.sh
log_step "Configuring system-wide profile (/etc/profile.d/burnandbuild.sh)..."
cat << 'EOF' > /etc/profile.d/burnandbuild.sh
# Auto-generated by BurnAndBuild Automation

# Standard Tool Homes
export ANDROID_HOME="/opt/android-sdk"
export ANDROID_SDK_ROOT="/opt/android-sdk"
export FLUTTER_HOME="/opt/flutter"
export WORKSPACE="/workspace"

# Global PATH additions
export PATH="/opt/flutter/bin:/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/build-tools/34.0.0:/opt/gradle/bin:/usr/local/bin:$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

# Developer Aliases
alias ll='ls -laF --color=auto'
alias la='ls -A --color=auto'
alias l='ls -CF --color=auto'
alias dc='docker compose'
alias gstatus='git status -sb'
alias burnandbuild='sudo /workspace/burnandbuild.sh'
alias reload='source /etc/profile.d/burnandbuild.sh && source ~/.bashrc 2>/dev/null'
EOF

chmod 644 /etc/profile.d/burnandbuild.sh

# 2. Append to User ~/.bashrc if not already present
USER_BASHRC="$TARGET_HOME/.bashrc"
if [ -f "$USER_BASHRC" ]; then
    if ! grep -q "burnandbuild.sh" "$USER_BASHRC"; then
        log_step "Linking BurnAndBuild profile to $USER_BASHRC..."
        cat << 'EOF' >> "$USER_BASHRC"

# Load BurnAndBuild Environment
if [ -f /etc/profile.d/burnandbuild.sh ]; then
    . /etc/profile.d/burnandbuild.sh
fi
EOF
    fi
fi

# 3. Append to User ~/.zshrc if exists
USER_ZSHRC="$TARGET_HOME/.zshrc"
if [ -f "$USER_ZSHRC" ]; then
    if ! grep -q "burnandbuild.sh" "$USER_ZSHRC"; then
        log_step "Linking BurnAndBuild profile to $USER_ZSHRC..."
        cat << 'EOF' >> "$USER_ZSHRC"

# Load BurnAndBuild Environment
if [ -f /etc/profile.d/burnandbuild.sh ]; then
    . /etc/profile.d/burnandbuild.sh
fi
EOF
    fi
fi

log_success "Phase 9: Shell profile and developer aliases configured."
