# scripts/08-Shell-Profile.ps1
# Configures PowerShell profile with posh-git, PSReadLine prediction, aliases, and reload helpers

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string[]]$SelectedTools = @()
)

$scriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
if (-not $scriptDir) { $scriptDir = (Get-Location).Path }
$rootDir = Split-Path -Path $scriptDir -Parent
$modulesPath = Join-Path -Path $rootDir -ChildPath "modules"
Import-Module (Join-Path -Path $modulesPath -ChildPath "Logging.psm1") -Global -DisableNameChecking

Write-LogHeader "Phase 9: PowerShell Environment and Shell Customization"

# 1. Check PowerShell Modules (posh-git, PSReadLine)
Write-Log -Level INFO -Message "Checking PowerShell environment and modules..."
try {
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    if (Get-Module -ListAvailable -Name posh-git) {
        Write-Log -Level SUCCESS -Message "posh-git is available."
    } else {
        Write-Log -Level INFO -Message "posh-git is not installed (shell profile handles this conditionally)."
    }
} catch {
    Write-Log -Level DEBUG -Message "Module check notice: $_"
}

# 2. Deploy Standard Profile
$profileTemplate = @'
# Modern Windows Developer Shell Profile
# Auto-generated by VM-Setup Automation

# Set console encoding to UTF-8
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

# PSReadLine Enhanced Prediction & History
if (Get-Module -ListAvailable -Name PSReadLine) {
    try {
        Import-Module PSReadLine -ErrorAction SilentlyContinue
        $psr = Get-Module PSReadLine
        if ($psr -and $psr.Version -ge [Version]"2.2.0") {
            Set-PSReadLineOption -PredictionSource HistoryAndPlugin -ErrorAction SilentlyContinue
            Set-PSReadLineOption -PredictionViewStyle ListView -ErrorAction SilentlyContinue
        }
        Set-PSReadLineOption -EditMode Windows -ErrorAction SilentlyContinue
        Set-PSReadLineKeyHandler -Key Tab -Function Complete -ErrorAction SilentlyContinue
    } catch {}
}

# Load posh-git for Git status in prompt
if (Get-Module -ListAvailable -Name posh-git) {
    Import-Module posh-git
}

# Load fnm if installed
if (Get-Command "fnm.exe" -ErrorAction SilentlyContinue) {
    & fnm env --use-on-cd | Out-String | Invoke-Expression
}

# Developer Aliases
Set-Alias -Name ll -Value Get-ChildItem -Option AllScope
function g { git $args }
function code. { code . }
function which ($name) { Get-Command $name -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source }

# Instant Environment Reload Helper
function reload-env {
    Write-Host "Reloading environment variables from registry..." -ForegroundColor Cyan
    foreach ($level in "Machine", "User") {
        [System.Environment]::GetEnvironmentVariables($level).GetEnumerator() | ForEach-Object {
            if ($_.Key -notmatch "^(?i:Path)$") {
                [System.Environment]::SetEnvironmentVariable($_.Key, $_.Value, "Process")
            }
        }
    }
    $m = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
    $u = [System.Environment]::GetEnvironmentVariable("Path", "User")
    $env:Path = (@($m -split ';', $u -split ';') | Where-Object { $_ -ne '' } | Select-Object -Unique) -join ';'
    Write-Host "Environment refreshed!" -ForegroundColor Green
}
'@

$allHostsProf = $PROFILE.CurrentUserAllHosts
if ($allHostsProf) {
    $dir = Split-Path -Path $allHostsProf -Parent
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    Set-Content -Path $allHostsProf -Value $profileTemplate -Encoding UTF8 -Force
    Write-Log -Level SUCCESS -Message "Deployed profile configuration to: $allHostsProf"
}

# Clean CurrentUserCurrentHost if it exists and differs from AllHosts to prevent duplicate banner/execution
$currHostProf = $PROFILE.CurrentUserCurrentHost
if ($currHostProf -and ($currHostProf -ne $allHostsProf) -and (Test-Path $currHostProf)) {
    Set-Content -Path $currHostProf -Value "# Host-specific profile - general developer profile loaded from profile.ps1" -Encoding UTF8 -Force
    Write-Log -Level SUCCESS -Message "Cleaned redundant host-specific profile at: $currHostProf"
}

Write-Log -Level SUCCESS -Message "PowerShell developer profile configured."
