# scripts/08-Shell-Profile.ps1
# Configures PowerShell profile with posh-git, PSReadLine prediction, aliases, and reload helpers

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string[]]$SelectedTools = @()
)

$modulesPath = Join-Path -Path $PSScriptRoot -ChildPath "..\modules"
Import-Module (Join-Path -Path $modulesPath -ChildPath "Logging.psm1") -Force

Write-LogHeader "Phase 8: PowerShell Environment and Shell Customization"

# 1. Install Helpful PowerShell Modules (posh-git, PSReadLine)
Write-Log -Level INFO -Message "Verifying PowerShell Gallery modules (posh-git, PSReadLine)..."
try {
    # Ensure NuGet provider is ready
    if (-not (Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue)) {
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Confirm:$false | Out-Null
    }

    if (-not (Get-Module -ListAvailable -Name posh-git)) {
        Write-Log -Level INFO -Message "Installing module 'posh-git'..."
        Install-Module -Name posh-git -Scope CurrentUser -Force -SkipPublisherCheck -Confirm:$false
    }
} catch {
    Write-Log -Level WARN -Message "Module installation from PSGallery had a warning: $_"
}

# 2. Deploy Standard Profile
$profileTemplate = @'
# Modern Windows Developer Shell Profile
# Auto-generated by VM-Setup Automation

# Set console encoding to UTF-8
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

# PSReadLine Enhanced Prediction & History
if (Get-Module -ListAvailable -Name PSReadLine) {
    Import-Module PSReadLine
    Set-PSReadLineOption -PredictionSource HistoryAndPlugin
    Set-PSReadLineOption -PredictionViewStyle ListView
    Set-PSReadLineOption -EditMode Windows
    Set-PSReadLineKeyHandler -Key Tab -Function Complete
}

# Load posh-git for Git status in prompt
if (Get-Module -ListAvailable -Name posh-git) {
    Import-Module posh-git
}

# Load fnm if installed
if (Get-Command "fnm.exe" -ErrorAction SilentlyContinue) {
    & fnm env --use-on-cd | Out-String | Invoke-Expression
}

# Developer Aliases
Set-Alias -Name ll -Value Get-ChildItem -Option AllScope
function g { git $args }
function code. { code . }
function which ($name) { Get-Command $name -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source }

# Instant Environment Reload Helper
function reload-env {
    Write-Host "Reloading environment variables from registry..." -ForegroundColor Cyan
    foreach ($level in "Machine", "User") {
        [System.Environment]::GetEnvironmentVariables($level).GetEnumerator() | ForEach-Object {
            if ($_.Key -notmatch "^(?i:Path)$") {
                [System.Environment]::SetEnvironmentVariable($_.Key, $_.Value, "Process")
            }
        }
    }
    $m = [System.Environment]::GetEnvironmentVariable("Path", "Machine")
    $u = [System.Environment]::GetEnvironmentVariable("Path", "User")
    $env:Path = (@($m -split ';', $u -split ';') | Where-Object { $_ -ne '' } | Select-Object -Unique) -join ';'
    Write-Host "Environment refreshed!" -ForegroundColor Green
}

Write-Host "Disposable Windows Dev VM Ready." -ForegroundColor Green
'@

$targetProfiles = @(
    $PROFILE.CurrentUserAllHosts,
    $PROFILE.CurrentUserCurrentHost
)

foreach ($prof in $targetProfiles) {
    if (-not $prof) { continue }
    $dir = Split-Path -Path $prof -Parent
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }

    Set-Content -Path $prof -Value $profileTemplate -Encoding UTF8 -Force
    Write-Log -Level SUCCESS -Message "Deployed profile configuration to: $prof"
}

Write-Log -Level SUCCESS -Message "PowerShell developer profile configured."
